In [1]:
%matplotlib notebook

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.model_selection import train_test_split

In [3]:
df=pd.read_csv("auxiliary-data/sg-population-demographics.csv")

In [4]:
df

     plannin_area                 subzone age_group sex  count
0      ang mo kio  ang mo kio town centre       0-4   m    130
1      ang mo kio               cheng san       0-4   m    670
2      ang mo kio              chong boon       0-4   m    460
3      ang mo kio             kebun bahru       0-4   m    380
4      ang mo kio         sembawang hills       0-4   m     90
...           ...                     ...       ...  ..    ...
7831       yishun              springleaf       85+   f     30
7832       yishun          yishun central       85+   f     10
7833       yishun             yishun east       85+   f    160
7834       yishun            yishun south       85+   f    240
7835       yishun             yishun west       85+   f    360

[7836 rows x 5 columns]

In [5]:
values=df["plannin_area"].unique()
print(np.sort(values))

['ang mo kio' 'bedok' 'bishan' 'bukit batok' 'bukit merah' 'bukit panjang'
 'bukit timah' 'changi' 'choa chu kang' 'clementi' 'downtown core'
 'geylang' 'hougang' 'jurong east' 'jurong west' 'kallang' 'mandai'
 'marine parade' 'museum' 'newton' 'novena' 'orchard' 'outram' 'pasir ris'
 'punggol' 'queenstown' 'river valley' 'rochor' 'seletar' 'sembawang'
 'sengkang' 'serangoon' 'singapore river' 'southern islands'
 'sungei kadut' 'tampines' 'tanglin' 'toa payoh' 'western water catchment'
 'woodlands' 'yishun']

In [6]:
values=df["subzone"].unique()
print(np.sort(values))

['admiralty' 'alexandra hill' 'alexandra north' 'aljunied' 'anak bukit'
 'anchorvale' 'ang mo kio town centre' 'balestier' 'bangkit' 'bayshore'
 'bedok north' 'bedok reservoir' 'bedok south' 'bencoolen' 'bendemeer'
 'bishan east' 'boat quay' 'boon keng' 'boon lay place' 'boon teck'
 'boulevard' 'braddell' 'bugis' 'bukit batok central' 'bukit batok east'
 'bukit batok south' 'bukit batok west' 'bukit ho swee' 'bukit merah'
 'cairnhill' 'cecil' 'central subzone' 'changi point' 'changi west'
 'chatsworth' 'cheng san' 'china square' 'chinatown'
 'choa chu kang central' 'choa chu kang north' 'chong boon' 'clarke quay'
 'clementi central' 'clementi north' 'clementi west' 'clementi woods'
 'commonwealth' 'compassvale' 'coronation road' 'crawford' 'dairy farm'
 'depot road' 'dhoby ghaut' 'dover' 'dunearn' 'everton park' 'faber'
 'fajar' 'farrer court' 'farrer park' 'fernvale' 'flora drive'
 'fort canning' 'frankel' 'gali batu' 'geylang bahru' 'geylang east'
 'ghim moh' 'gombak' 'goodwood park' 'guilin' 'henderson hill' 'hillcrest'
 'hillview' 'holland drive' 'holland road' 'hong kah' 'hong kah north'
 'hougang central' 'hougang east' 'hougang west' 'institution hill'
 'jelebu' 'joo seng' 'jurong west central' 'kaki bukit' 'kampong bugis'
 'kampong glam' 'kampong java' 'kampong tiong bahru' 'kampong ubi'
 'kangkar' 'katong' 'keat hong' 'kebun bahru' 'kembangan' 'kent ridge'
 'khatib' 'kim keat' 'kovan' 'lakeside' 'lavender' 'leedon park'
 'leonie hill' 'little india' 'lorong 8 toa payoh' 'lorong ah soo'
 'lorong chuan' 'lower seletar' 'loyang east' 'loyang west' 'mackenzie'
 'macpherson' 'malcolm' 'mandai estate' 'margaret drive' 'marine parade'
 'maritime square' 'marymount' 'matilda' 'mei chin' 'midview'
 "monk's hill" 'moulmein' 'mount emily' 'mount pleasant' 'mountbatten'
 'nassim' "national university of s'pore" 'nature reserve' 'nee soon'
 'newton circus' 'north coast' 'northland' 'northshore' 'one north'
 'one tree hill' 'orange grove' 'oxley' 'pasir panjang 1'
 'pasir panjang 2' 'pasir ris central' 'pasir ris drive' 'pasir ris park'
 'pasir ris west' 'paterson' "pearl's hill" 'pei chun' 'peng siang'
 "people's park" 'port' 'potong pasir' 'punggol field'
 'punggol town centre' 'queensway' 'redhill' 'ridout' 'rivervale'
 'robertson quay' 'saujana' 'selegie' 'seletar' 'seletar hills'
 'sembawang central' 'sembawang hills' 'sembawang north'
 'sembawang springs' 'sembawang straits' 'sengkang town centre' 'senja'
 'sennett' 'sentosa' 'serangoon central' 'serangoon garden'
 'serangoon north' 'shangri-la' 'siglap' 'simei' 'singapore polytechnic'
 'somerset' 'springleaf' 'sungei road' 'sunset way' 'swiss club' 'tagore'
 'tai seng' 'taman jurong' 'tampines east' 'tampines west' 'tanglin'
 'tanglin halt' 'tanjong pagar' 'tanjong rhu' 'teban gardens' 'teck whye'
 'telok blangah drive' 'telok blangah rise' 'telok blangah way'
 'tiong bahru' 'tiong bahru station' 'toa payoh central' 'toa payoh west'
 'toh guan' 'townsville' 'trafalgar' 'turf club' 'tyersall' 'ulu pandan'
 'upper paya lebar' 'upper thomson' 'victoria' 'waterway east' 'wenya'
 'west coast' 'western water catchment' 'woodgrove' 'woodlands east'
 'woodlands south' 'woodlands west' 'woodleigh' 'xilin' 'yew tee'
 'yio chu kang east' 'yio chu kang west' 'yishun central' 'yishun east'
 'yishun south' 'yishun west' 'yuhua east' 'yuhua west' 'yunnan']

In [7]:
values=df["age_group"].unique()
print(np.sort(values))

['0-4' '10-14' '15-19' '20-24' '25-29' '30-34' '35-39' '40-44' '45-49'
 '5-9' '50-54' '55-59' '60-64' '65-69' '70-74' '75-79' '80-84' '85+']

In [8]:
values=df["sex"].unique()
print(np.sort(values))

['f' 'm']

In [9]:
df_new = df.groupby(['plannin_area', 'age_group'])['count'].agg('sum').reset_index()

In [10]:
df_new.head()

  plannin_area age_group  count
0   ang mo kio       0-4   6790
1   ang mo kio     10-14   8300
2   ang mo kio     15-19   9340
3   ang mo kio     20-24  10310
4   ang mo kio     25-29  11180

In [11]:
df['0-4'] = df['count'].where(df['age_group'] == '0-4')
df['5-9'] = df['count'].where(df['age_group'] == '5-9')
df['10-14'] = df['count'].where(df['age_group'] == '10-14')
df['15-19'] = df['count'].where(df['age_group'] == '15-19')
df['20-24'] = df['count'].where(df['age_group'] == '20-24')
df['25-29'] = df['count'].where(df['age_group'] == '25-29')
df['30-34'] = df['count'].where(df['age_group'] == '30-34')
df['35-39'] = df['count'].where(df['age_group'] == '35-39')
df['40-44'] = df['count'].where(df['age_group'] == '40-44')
df['45-49'] = df['count'].where(df['age_group'] == '45-49')
df['50-54'] = df['count'].where(df['age_group'] == '50-54')
df['55-59'] = df['count'].where(df['age_group'] == '55-59')
df['60-64'] = df['count'].where(df['age_group'] == '60-64')
df['65-69'] = df['count'].where(df['age_group'] == '65-69')
df['70-74'] = df['count'].where(df['age_group'] == '70-74')
df['75-79'] = df['count'].where(df['age_group'] == '75-79')
df['80-84'] = df['count'].where(df['age_group'] == '80-84')
df['85+'] = df['count'].where(df['age_group'] == '85+')
df.iloc[300:320]

,plannin_area,subzone,age_group,sex,count,0-4,5-9,10-14,15-19,20-24,...,40-44,45-49,50-54,55-59,60-64,65-69,70-74,75-79,80-84,85+
300,hougang,hougang west,5-9,m,1010,NaN,1010.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
301,hougang,kangkar,5-9,m,580,NaN,580.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
302,hougang,kovan,5-9,m,610,NaN,610.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
303,hougang,lorong ah soo,5-9,m,690,NaN,690.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
304,hougang,tai seng,5-9,m,360,NaN,360.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305,hougang,trafalgar,5-9,m,1220,NaN,1220.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
306,jurong east,lakeside,5-9,m,20,NaN,20.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307,jurong east,teban gardens,5-9,m,460,NaN,460.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
308,jurong east,toh guan,5-9,m,390,NaN,390.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
309,jurong east,yuhua east,5-9,m,590,NaN,590.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
310,jurong east,yuhua west,5-9,m,500,NaN,500.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
311,jurong west,boon lay place,5-9,m,950,NaN,950.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
312,jurong west,hong kah,5-9,m,1320,NaN,1320.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,jurong west,jurong west central,5-9,m,2530,NaN,2530.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,jurong west,taman jurong,5-9,m,1050,NaN,1050.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,jurong west,wenya,5-9,m,400,NaN,400.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,jurong west,yunnan,5-9,m,1870,NaN,1870.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
317,kallang,bendemeer,5-9,m,770,NaN,770.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
318,kallang,boon keng,5-9,m,200,NaN,200.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319,kallang,crawford,5-9,m,160,NaN,160.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df=df.drop(columns=["subzone","age_group","sex","count"])
df.head()

,plannin_area,0-4,5-9,10-14,15-19,20-24,25-29,30-34,35-39,40-44,45-49,50-54,55-59,60-64,65-69,70-74,75-79,80-84,85+
0,ang mo kio,130.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ang mo kio,670.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ang mo kio,460.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ang mo kio,380.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ang mo kio,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
aggregations = {
    '0-4':'sum',
    '5-9':'sum',
    '10-14':'sum',
    '15-19':'sum',
    '20-24':'sum',
    '25-29':'sum',
    '30-34':'sum',
    '35-39':'sum',
    '40-44':'sum',
    '45-49':'sum',
    '50-54':'sum',
    '55-59':'sum',
    '60-64':'sum',
    '65-69':'sum',
    '70-74':'sum',
    '75-79':'sum',
    '80-84':'sum',
    '85+':'sum',
}

In [20]:
df.groupby('plannin_area').agg(aggregations)

,0-4,5-9,10-14,15-19,20-24,25-29,30-34,35-39,40-44,45-49,50-54,55-59,60-64,65-69,70-74,75-79,80-84,85+
plannin_area,,,,,,,,,,,,,,,,,,
ang mo kio,6790.0,7680.0,8300.0,9340.0,10310.0,11180.0,12240.0,13080.0,13720.0,13000.0,14020.0,13810.0,13000.0,11050.0,6680.0,5150.0,3240.0,2330.0
bedok,11690.0,13420.0,14770.0,16940.0,19480.0,19870.0,19290.0,20850.0,22540.0,21450.0,23420.0,23360.0,20580.0,16740.0,9330.0,7340.0,4770.0,4010.0
bishan,3430.0,4330.0,4720.0,5530.0,6870.0,6470.0,5720.0,5990.0,7070.0,6810.0,7540.0,7710.0,6360.0,4860.0,2730.0,2150.0,1370.0,1090.0
bukit batok,5510.0,6900.0,7960.0,9240.0,10090.0,10460.0,9770.0,9960.0,10990.0,11320.0,12190.0,11780.0,9380.0,6000.0,3050.0,2250.0,1460.0,1110.0
bukit merah,7220.0,7470.0,6650.0,6860.0,7730.0,9360.0,11120.0,12840.0,12730.0,11320.0,11340.0,11760.0,10940.0,10060.0,6480.0,5610.0,3530.0,3060.0
bukit panjang,7320.0,7620.0,8470.0,9420.0,10400.0,10990.0,10680.0,10040.0,11180.0,10560.0,11630.0,10680.0,7900.0,5200.0,2750.0,2010.0,1310.0,1040.0
bukit timah,3120.0,4660.0,4820.0,4820.0,4990.0,4300.0,3780.0,4950.0,6630.0,6340.0,5820.0,5330.0,4550.0,3950.0,2380.0,1900.0,1240.0,1010.0
changi,180.0,230.0,220.0,160.0,130.0,110.0,170.0,240.0,300.0,220.0,140.0,110.0,100.0,80.0,50.0,30.0,30.0,40.0
choa chu kang,7190.0,9350.0,11380.0,14820.0,15250.0,11940.0,11530.0,11970.0,13720.0,16000.0,16190.0,12910.0,8830.0,5660.0,2990.0,2220.0,1430.0,1050.0
clementi,3910.0,4410.0,4490.0,4680.0,4870.0,5830.0,6640.0,7310.0,7610.0,6950.0,6970.0,6560.0,6650.0,6200.0,3360.0,2600.0,1480.0,1210.0
downtown core,100.0,80.0,80.0,130.0,120.0,210.0,310.0,340.0,330.0,320.0,260.0,280.0,250.0,230.0,130.0,120.0,60.0,110.0
geylang,4470.0,5350.0,5420.0,6320.0,7540.0,8130.0,8180.0,8720.0,9010.0,8790.0,9620.0,9630.0,8060.0,6470.0,3890.0,3310.0,2250.0,1840.0
hougang,8400.0,10040.0,11680.0,14380.0,16840.0,16660.0,15020.0,14850.0,16700.0,17010.0,19600.0,19290.0,15060.0,10850.0,5970.0,4690.0,3050.0,2360.0
jurong east,3270.0,3880.0,4550.0,4990.0,5760.0,6580.0,6370.0,6080.0,6540.0,6240.0,6720.0,7020.0,6420.0,4760.0,2380.0,1710.0,1040.0,760.0
jurong west,13580.0,15910.0,16710.0,18030.0,19080.0,19940.0,22560.0,23420.0,23070.0,21680.0,20670.0,19120.0,15860.0,10830.0,5250.0,3570.0,2110.0,1420.0
kallang,4350.0,4460.0,4490.0,4750.0,5140.0,6130.0,7250.0,8280.0,8610.0,7780.0,7820.0,7840.0,7060.0,6100.0,3900.0,3410.0,2140.0,1800.0
mandai,90.0,120.0,150.0,170.0,150.0,140.0,140.0,170.0,190.0,180.0,160.0,140.0,90.0,80.0,60.0,40.0,20.0,20.0
marine parade,2190.0,2700.0,2680.0,2610.0,2690.0,2600.0,2870.0,3860.0,4580.0,3830.0,3670.0,3380.0,2910.0,2770.0,1790.0,1650.0,1030.0,940.0
museum,20.0,20.0,0.0,10.0,10.0,10.0,30.0,60.0,50.0,40.0,40.0,30.0,10.0,10.0,0.0,0.0,0.0,0.0
newton,320.0,480.0,330.0,340.0,330.0,340.0,400.0,570.0,730.0,650.0,600.0,490.0,430.0,380.0,180.0,170.0,110.0,110.0
novena,2270.0,2780.0,2500.0,2550.0,2580.0,2650.0,3030.0,3980.0,4540.0,3900.0,3720.0,3360.0,2860.0,2450.0,1580.0,1380.0,980.0,930.0
orchard,40.0,50.0,40.0,30.0,20.0,60.0,60.0,60.0,90.0,90.0,80.0,90.0,70.0,70.0,20.0,30.0,0.0,0.0
outram,1300.0,1070.0,700.0,740.0,820.0,1150.0,1690.0,2130.0,1720.0,1480.0,1590.0,1650.0,1590.0,1460.0,940.0,860.0,540.0,610.0
pasir ris,5770.0,7080.0,9020.0,12340.0,13430.0,9120.0,7980.0,9080.0,10380.0,12950.0,14090.0,10480.0,7050.0,4460.0,2350.0,1900.0,1340.0,1150.0
punggol,12000.0,9210.0,6200.0,4450.0,3950.0,6760.0,15690.0,13410.0,10600.0,6490.0,5540.0,4730.0,3960.0,3040.0,1570.0,1050.0,660.0,510.0
queenstown,4460.0,4490.0,4350.0,4780.0,5320.0,6180.0,7150.0,7670.0,8070.0,7630.0,7530.0,6720.0,6140.0,5920.0,3950.0,3680.0,2410.0,1770.0
river valley,420.0,530.0,520.0,410.0,490.0,510.0,640.0,870.0,1060.0,890.0,680.0,620.0,500.0,470.0,260.0,180.0,100.0,130.0
rochor,530.0,570.0,570.0,620.0,680.0,890.0,1060.0,1300.0,1270.0,1080.0,1120.0,1130.0,1060.0,920.0,630.0,510.0,360.0,400.0
seletar,10.0,20.0,20.0,20.0,10.0,0.0,0.0,20.0,40.0,40.0,40.0,20.0,20.0,0.0,0.0,0.0,0.0,0.0
sembawang,4460.0,5400.0,5370.0,4810.0,4480.0,5130.0,6390.0,7190.0,7630.0,6090.0,5660.0,4890.0,3430.0,2210.0,1290.0,930.0,610.0,490.0
sengkang,15340.0,15180.0,12640.0,11840.0,10870.0,14320.0,21120.0,21100.0,19240.0,14690.0,13630.0,12640.0,9280.0,6440.0,3360.0,2420.0,1450.0,1170.0
serangoon,4090.0,5090.0,6220.0,7750.0,9160.0,9050.0,7520.0,7480.0,8530.0,8770.0,10050.0,10800.0,9160.0,6850.0,3690.0,3010.0,1940.0,1670.0
singapore river,200.0,170.0,120.0,90.0,80.0,80.0,280.0,370.0,420.0,280.0,200.0,130.0,100.0,90.0,50.0,30.0,0.0,30.0
southern islands,90.0,80.0,90.0,80.0,90.0,70.0,60.0,120.0,160.0,200.0,180.0,100.0,70.0,40.0,20.0,20.0,0.0,0.0
sungei kadut,30.0,20.0,40.0,50.0,40.0,50.0,40.0,40.0,40.0,60.0,50.0,70.0,50.0,70.0,50.0,50.0,30.0,50.0
tampines,11210.0,12260.0,13810.0,18190.0,21390.0,20420.0,18820.0,18010.0,18310.0,19840.0,22820.0,22490.0,17360.0,11480.0,5490.0,4320.0,2830.0,2250.0
tanglin,940.0,1300.0,1100.0,1020.0,950.0,880.0,1140.0,1570.0,2000.0,1800.0,1520.0,1270.0,1130.0,930.0,540.0,380.0,250.0,270.0
toa payoh,5030.0,5670.0,5750.0,6470.0,7370.0,7630.0,8440.0,9050.0,10170.0,9450.0,9730.0,9910.0,8310.0,7430.0,5030.0,4530.0,2830.0,2380.0
western water catchment,50.0,40.0,60.0,40.0,130.0,80.0,50.0,80.0,100.0,60.0,70.0,60.0,30.0,10.0,20.0,0.0,10.0,30.0
woodlands,11960.0,14430.0,17010.0,21030.0,20060.0,17910.0,18450.0,18670.0,21110.0,22220.0,21050.0,16810.0,11620.0,7650.0,4050.0,3100.0,1890.0,1250.0
yishun,10220.0,9970.0,10450.0,12180.0,14640.0,17020.0,17040.0,15440.0,15120.0,14950.0,17360.0,15960.0,12320.0,8350.0,4440.0,3180.0,1950.0,1470.0